### ISSUE TITLE
홍보

### ISSUE THREAD

**Issue by SeunghyunKing** [HyeJinP/os_second_project#6]
https://www.reddit.com/user/thdgusdlf/comments/7gjv38/we_made_a_cardnews_website_please_visit_our/

**Comment by HyeJinP** [comment]
https://www.reddit.com/r/opensource/comments/7gdgyx/please_evaluate_the_project_progress_in_the/

**Comment by HyeJinP** [comment]
https://okky.kr/article/427935

**Comment by HyeJinP** [comment]
https://news.ycombinator.com/item?id=15806964
